### ISSUE TITLE
Externalizar os nomes de empresas para um server elasticsearch

### ISSUE THREAD

**Issue by ricardovsilva** [carlosmaniero/patrocina-rodeios#10]
A ideia é permitir buscas fonéticas ou mesmo erradas. Hoje se o usuário errar a forma de digitar uma empresa, ela não será exibida.
Minha ideia ao ir para um server elasticsearch é permitir que a busca seja feita mesmo quando algo for digitado de forma errada.
Além disso, seria um passo para externalizar os nomes de empresas do arquivo json para uma base de dados.

**Comment by carlosmaniero** [comment]
Como dito no #11 esse é um MVP. Hoje ele tá lendo um json estático. 

Se eu sentir que vale à pena investir esforço no back-end eu abro um novo projeto.

De qualquer forma, é bem viável implementar uma busca fuzzy search em Elm.
Hoje os filtros encontram-se nesse módulo. https://github.com/carlosmaniero/patrocina-rodeios/blob/master/src/Search/Filters.elm
