### ISSUE TITLE
Ao invés de redirecionar, abrir a informação da empresa na própria página

### ISSUE THREAD

**Issue by ricardovsilva** [carlosmaniero/patrocina-rodeios#11]
Na página de listagem de empresas, quando o usuário clica em uma empresa ele é redirecionado a uma página que não tem mais nada, somente o descritivo da participação da empresa.
Isso poderia aparecer na própria listagem da empresa, usando um efeito accordion talvez. Não vejo necessidade real de redirecionar para outra página. O que acha?

**Comment by ricardovsilva** [comment]
A fim de exemplificar a ideia apresentada acima:

![image](https://user-images.githubusercontent.com/2130182/31896119-b816ec5c-b7f1-11e7-84f9-8faac3ee8ecd.png)

**Comment by carlosmaniero** [comment]
Acho legal, mas a ideia de gerar um link é basicamente para ter um link compartilhável.

Eu prefiro esperar o site ter uma quantidade rasoável de visitas e tentar entender o comportamento das pessoas. Minha hipótese é que as pessoas só clicaram para pegar o link da página, não pra ler o conteúdo em si. Mas eu posso estar errado.

Lembrando que esse é um MVP de uma semana e que as ideias são bem vindas. Nesse primeiro momento o mais importante é ver como as pessoas interagem com o site.
