### ISSUE TITLE
Expandir para empresas que praticam qualquer tipo de maus tratos com animais

### ISSUE THREAD

**Issue by ricardovsilva** [carlosmaniero/patrocina-rodeios#9]
O que acha de mudarmos o sistema, e expandi-lo, para que contenham informações de quaisquer empresas que praticam qualquer tipo de maus tratos com animais (e não somente rodeios).
Minha ideia é que se torne uma plataforma colaborativa, onde qualquer um possa fazer uma denúncia ou submeter informações, e a partir disso alguns moderadores aceitam ou não a informação.

**Comment by carlosmaniero** [comment]
Minha ideia com é gerar vários projetos pequenos para não ficar algo inalcançável já que isso é um trabalho que faço nas minhas horas livres. 

Mas de fato o projeto final, seria um agregador que mostre se um deterninado produto é vegano ou não. 

Pela ordem o próximo seria, empresas que testam ou não em animais.
